# Generated by Django 4.2.4 on 2023-10-02 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('run', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('cant_alum', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=4000)),
                ('imagen', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id_notas', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nota1', models.FloatField(null=True)),
                ('nota2', models.FloatField(null=True)),
                ('nota3', models.FloatField(null=True)),
                ('nota4', models.FloatField(null=True)),
                ('nota5', models.FloatField(null=True)),
                ('nota6', models.FloatField(null=True)),
                ('promedio', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('run', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=20)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id_plan', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('obj_clase', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('act_semestre', models.TextField(max_length=3000)),
                ('profesor_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('run', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nac', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField()),
                ('inf_adicional', models.TextField(max_length=300)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.curso')),
            ],
        ),
    ]
