# Generated by Django 4.2.4 on 2023-10-23 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('cant_alum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id_notas', models.AutoField(primary_key=True, serialize=False)),
                ('nota1', models.FloatField(null=True)),
                ('nota2', models.FloatField(null=True)),
                ('nota3', models.FloatField(null=True)),
                ('nota4', models.FloatField(null=True)),
                ('nota5', models.FloatField(null=True)),
                ('nota6', models.FloatField(null=True)),
                ('promedio', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=20)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('run', models.AutoField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.comuna')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('obj_clase', models.TextField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('act_semestre', models.TextField(max_length=3000)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.TextField(max_length=300)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=500)),
                ('imagen', models.BinaryField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('run', models.AutoField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.comuna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('run', models.AutoField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nac', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('inf_adicional', models.TextField(max_length=300)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.apoderado')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.comuna')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.curso')),
                ('notas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.notas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaEducacion.usuario')),
            ],
        ),
    ]
